// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "cellar": public TestHelpers
//
// Command:
// $ goagen
// --design=github.com/podhmo/apiserver-examples/usegoa/design
// --out=$(GOPATH)/src/github.com/podhmo/apiserver-examples/usegoa
// --version=v1.3.1

package test
